<?php


$mapeoRutas =
  array('inicio' =>
          array('controller' =>'defaultController', 'action' =>'inicio'),
          'login' =>
          array('controller' =>'loginController', 'action' =>'login'),
          'logout' =>
          array('controller' =>'loginController', 'action' =>'logout'),
          'vistaFichaje' =>
          array('controller' =>'ficharController', 'action' =>'vistaFichaje'),
       );


  
